### ISSUE TITLE
List of Contributors

### ISSUE THREAD

**Issue by VighneshPath** [pccoeacm/sandbox#19]
Adding a list of contributors like this
![c](https://user-images.githubusercontent.com/59459766/93707470-86732200-fb4c-11ea-98bd-84b27109caf8.PNG)
will encourage more people to contribute.

**Comment by tejasmorkar** [comment]
Are you working on it?

**Comment by VighneshPath** [comment]
Yeah, I had added the javascript, but I think a commit from someone overwrote all new changes by everyone
